import React, { useEffect } from 'react';
import Head from 'next/head';
import Router from 'next/router';

import Header from '../components/Header'

export default function Home() {
	useEffect(() => { Router.push('/product/manage'); }, []);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="Home">
				<Header title="Home" />
			</div>
		</>
	)
}
